# Generated by Django 2.0.4 on 2019-05-17 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatViz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pause',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='nb',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='real_duration',
        ),
        migrations.AddField(
            model_name='task',
            name='pause_duration',
            field=models.DurationField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='project_name',
            field=models.CharField(default='defalut', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Pause',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
